apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: khongcon001/udagram-api-feed:v1
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1024Mi"
              cpu: "150m"
            limits:
              memory: "4096Mi"
              cpu: "800m"                  
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: env-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: backend-user
          image: khongcon001/udagram-api-user:v1
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1024Mi"
              cpu: "150m"
            limits:
              memory: "4096Mi"
              cpu: "800m"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: env-secret
